# Generated by Django 6.0.5 on 2026-05-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('credit_record_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='信用记录编号')),
                ('change_value', models.IntegerField(verbose_name='信用变动值')),
                ('reason', models.CharField(max_length=200, verbose_name='变动原因')),
            ],
            options={
                'verbose_name': '信用变动记录',
                'verbose_name_plural': '信用变动记录',
                'db_table': 'credit_record',
            },
        ),
    ]
