# Generated by Django 6.0.5 on 2026-05-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('asset_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='资产编号')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='持有数量')),
                ('acquire_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='入手价格')),
                ('acquired_at', models.DateTimeField(blank=True, null=True, verbose_name='入手时间')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前估值')),
                ('status', models.CharField(choices=[('holding', '持有中'), ('selling', '出售中'), ('exchanging', '换物中'), ('locked', '交易锁定'), ('sold', '已售出'), ('exchanged', '已换出'), ('invalid', '已失效')], default='holding', max_length=20, verbose_name='持有状态')),
                ('source', models.CharField(blank=True, default='', max_length=50, verbose_name='来源')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='products.product', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '用户资产',
                'verbose_name_plural': '用户资产',
                'db_table': 'user_asset',
            },
        ),
        migrations.CreateModel(
            name='AssetFlow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('flow_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='流水编号')),
                ('flow_type', models.CharField(choices=[('acquire', '获取'), ('transfer', '转让'), ('sell', '售出'), ('exchange_out', '换出'), ('exchange_in', '换入'), ('lock', '锁定'), ('unlock', '解锁'), ('invalidate', '失效')], max_length=20, verbose_name='流转类型')),
                ('related_order', models.CharField(blank=True, default='', max_length=25, verbose_name='关联订单')),
                ('related_exchange', models.CharField(blank=True, default='', max_length=25, verbose_name='关联换物')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_flows_out', to=settings.AUTH_USER_MODEL, verbose_name='来源用户')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_flows_in', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='assets.userasset', verbose_name='关联资产')),
            ],
            options={
                'verbose_name': '资产流转记录',
                'verbose_name_plural': '资产流转记录',
                'db_table': 'asset_flow',
            },
        ),
    ]
