# Generated by Django 3.2.24 on 2026-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasset',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='资产描述'),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='status',
            field=models.CharField(choices=[('holding', '持有中'), ('selling', '出售中'), ('exchanging', '换物中'), ('sold', '已售出'), ('invalid', '已失效')], default='holding', max_length=20, verbose_name='持有状态'),
        ),
    ]
