# Generated by Django 3.2.24 on 2026-05-27 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_update_asset_status_and_add_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
