# Generated by Django 6.0.5 on 2026-05-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('price_record_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='价格记录编号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价格或统计价格')),
                ('source', models.CharField(choices=[('order', '平台成交订单'), ('manual', '管理员录入'), ('system', '系统统计生成')], default='order', max_length=10, verbose_name='来源')),
                ('recorded_at', models.DateTimeField(verbose_name='统计时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品价格记录',
                'verbose_name_plural': '商品价格记录',
                'db_table': 'price_record',
            },
        ),
    ]
