# Generated by Django 6.0.5 on 2026-05-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('status', models.CharField(choices=[('created', '已创建'), ('pending_payment', '待支付'), ('paid', '已支付'), ('completed', '已完成'), ('cancelled', '已取消'), ('closed', '已关闭'), ('refunded', '已退款')], default='created', max_length=20, verbose_name='订单状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.listing', verbose_name='关联挂单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product', verbose_name='商品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('log_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='日志编号')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='变更前状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='变更后状态')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '订单状态变更记录',
                'verbose_name_plural': '订单状态变更记录',
                'db_table': 'order_status_log',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('payment_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='支付流水编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('pay_method', models.CharField(choices=[('balance', '余额支付'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('simulated', '模拟支付')], default='simulated', max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('third_trade_no', models.CharField(blank=True, default='', max_length=100, verbose_name='第三方交易流水号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='关联订单')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='支付用户')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payment_record',
            },
        ),
    ]
