# Generated by Django 6.0.5 on 2026-06-05 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_load_divisions"),
        ("market", "0002_alter_listing_asset"),
        ("orders", "0001_initial"),
        ("products", "0003_alter_product_main_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "order"},
        ),
        migrations.AlterModelOptions(
            name="orderstatuslog",
            options={
                "verbose_name": "order status log",
                "verbose_name_plural": "order status log",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentrecord",
            options={
                "verbose_name": "payment record",
                "verbose_name_plural": "payment record",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="receiver_name",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="receiver name"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="receiver_phone",
            field=models.CharField(
                blank=True, default="", max_length=11, verbose_name="receiver phone"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="addresses.address",
                verbose_name="shipping address",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                verbose_name="shipping address snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_as_buyer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="buyer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="completed at"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="market.listing",
                verbose_name="listing",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                max_length=25,
                primary_key=True,
                serialize=False,
                verbose_name="order id",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="products.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="order",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_as_seller",
                to=settings.AUTH_USER_MODEL,
                verbose_name="seller",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending_payment", "Pending payment"),
                    ("paid", "Paid"),
                    ("receiving", "Receiving"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("closed", "Closed"),
                    ("refunded", "Refunded"),
                ],
                default="created",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="from_status",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="from status"
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="log_id",
            field=models.CharField(
                max_length=30, primary_key=True, serialize=False, verbose_name="log id"
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="note",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="note"
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_status_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="operator",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="orders.order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="to_status",
            field=models.CharField(max_length=20, verbose_name="to status"),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="orders.order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="pay_method",
            field=models.CharField(
                choices=[
                    ("balance", "Balance"),
                    ("alipay", "Alipay"),
                    ("wechat", "Wechat"),
                    ("simulated", "Simulated"),
                ],
                default="simulated",
                max_length=20,
                verbose_name="pay method",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="payer",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_id",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="payment id",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="third_trade_no",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="third trade no"
            ),
        ),
    ]
