# Generated by Django 6.0.5 on 2026-06-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_listing_asset'),
        ('orders', '0002_alter_order_options_alter_orderstatuslog_options_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='teams.teamproject', verbose_name='team project'),
        ),
        migrations.AlterField(
            model_name='order',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.listing', verbose_name='listing'),
        ),
    ]
