# Generated by Django 6.0.5 on 2026-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderstatuslog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('receiving', 'Receiving'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('pending_return', 'Pending return'), ('refunded', 'Refunded')], default='created', max_length=20, verbose_name='status'),
        ),
    ]
