# Generated by Django 6.0.5 on 2026-06-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_team_alter_order_listing'),
        ('products', '0003_alter_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.product', verbose_name='product'),
        ),
    ]
