# Generated by Django 6.0.5 on 2026-06-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        ('orders', '0004_alter_order_product'),
    ]

    operations = [
    ]
