# Generated by Django 6.0.5 on 2026-05-23 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_id', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='用户编号')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='昵称')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('admin', '管理员')], default='user', max_length=10, verbose_name='角色')),
                ('credit_score', models.IntegerField(default=100, verbose_name='信用分')),
                ('status', models.CharField(choices=[('normal', '正常'), ('frozen', '冻结'), ('disabled', '停用'), ('deleted', '已注销')], default='normal', max_length=10, verbose_name='账户状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('avatar', models.URLField(blank=True, default='', verbose_name='头像')),
                ('bio', models.CharField(blank=True, default='', max_length=200, verbose_name='简介')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系方式')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'user_profile',
            },
        ),
    ]
