# Generated by Django 6.0.5 on 2026-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_revoked_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Token 吊销时间'),
        ),
    ]
