# Generated by Django 6.0.5 on 2026-05-23 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_id', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='商品编号')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('ip_name', models.CharField(max_length=50, verbose_name='IP 名称')),
                ('character_name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('category', models.CharField(choices=[('figure', '手办'), ('badge', '徽章'), ('poster', '海报'), ('acrylic', '亚克力'), ('doll', '玩偶'), ('card', '卡片'), ('other', '其他')], max_length=20, verbose_name='品类')),
                ('rarity', models.CharField(choices=[('common', '普通'), ('rare', '稀有'), ('sr', 'SR'), ('ssr', 'SSR'), ('limited', '限定')], max_length=20, verbose_name='稀有度')),
                ('reference_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='参考价格')),
                ('status', models.CharField(choices=[('active', '正常展示'), ('inactive', '下架'), ('frozen', '冻结'), ('archived', '归档')], default='active', max_length=10, verbose_name='商品状态')),
                ('main_image', models.URLField(blank=True, default='', verbose_name='主图')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image_url', models.URLField(verbose_name='图片地址')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'product_image',
                'ordering': ['sort_order'],
            },
        ),
    ]
