# Generated by Django 3.2.24 on 2026-05-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rarity',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='character_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', '正常启用'), ('inactive', '未启用'), ('frozen', '冻结'), ('archived', '已归档')], default='active', max_length=10, verbose_name='商品状态'),
        ),
    ]
