# Generated by Django 6.0.5 on 2026-06-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20260526_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='', upload_to='products/%Y/%m/', verbose_name='主图'),
        ),
    ]
