# Generated by Django 6.0.5 on 2026-05-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('team_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='拼团编号')),
                ('target_count', models.PositiveIntegerField(verbose_name='目标人数')),
                ('current_count', models.PositiveIntegerField(default=1, verbose_name='当前人数')),
                ('team_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='团购价格')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('status', models.CharField(choices=[('recruiting', '招募中'), ('success', '拼团成功'), ('failed', '拼团失败'), ('cancelled', '已取消')], default='recruiting', max_length=20, verbose_name='拼团状态')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_projects', to=settings.AUTH_USER_MODEL, verbose_name='发起用户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_projects', to='products.product', verbose_name='拼团商品')),
            ],
            options={
                'verbose_name': '拼团项目',
                'verbose_name_plural': '拼团项目',
                'db_table': 'team_project',
            },
        ),
        migrations.CreateModel(
            name='TeamParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('participant_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='参与记录编号')),
                ('status', models.CharField(choices=[('joined', '已参与'), ('cancelled', '已取消'), ('refunded', '已退款')], default='joined', max_length=20, verbose_name='参与状态')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='参与时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_participations', to=settings.AUTH_USER_MODEL, verbose_name='参与用户')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='teams.teamproject', verbose_name='关联拼团')),
            ],
            options={
                'verbose_name': '拼团参与记录',
                'verbose_name_plural': '拼团参与记录',
                'db_table': 'team_participant',
                'constraints': [models.UniqueConstraint(fields=('team', 'user'), name='unique_team_user')],
            },
        ),
    ]
