# Generated by Django 6.0.5 on 2026-06-05 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_main_image'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamproject',
            name='product_name',
            field=models.CharField(default='', max_length=100, verbose_name='拼团商品名称'),
        ),
        migrations.AlterField(
            model_name='teamproject',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_projects', to='products.product', verbose_name='关联商品'),
        ),
        migrations.CreateModel(
            name='TeamItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='选项编号')),
                ('name', models.CharField(max_length=100, verbose_name='选项名称')),
                ('selected_at', models.DateTimeField(blank=True, null=True, verbose_name='选中时间')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_team_items', to=settings.AUTH_USER_MODEL, verbose_name='选中用户')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='teams.teamproject', verbose_name='关联拼团')),
            ],
            options={
                'verbose_name': '拼团小商品选项',
                'verbose_name_plural': '拼团小商品选项',
                'db_table': 'team_item',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='teamparticipant',
            name='selected_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_participants', to='teams.teamitem', verbose_name='选中小商品'),
        ),
    ]
