# Generated by Django 6.0.5 on 2026-06-12 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_main_image'),
        ('teams', '0002_teamproject_product_name_alter_teamproject_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamproject',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_projects', to='products.product', verbose_name='关联商品'),
        ),
    ]
