# Generated by Django 6.0.5 on 2026-06-12 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_main_image'),
        ('teams', '0003_update_product_on_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamproject',
            name='product',
        ),
        migrations.AddField(
            model_name='teamitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_items', to='products.product', verbose_name='关联商品'),
        ),
        migrations.AlterField(
            model_name='teamproject',
            name='current_count',
            field=models.PositiveIntegerField(default=0, verbose_name='当前人数'),
        ),
    ]
