# Generated by Django 6.0.5 on 2026-05-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('listing_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='挂单编号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出售价格')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='出售数量')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '上架中'), ('locked', '已被订单锁定'), ('sold', '已售出'), ('cancelled', '已取消'), ('removed', '管理员下架')], default='active', max_length=20, verbose_name='挂单状态')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='assets.userasset', verbose_name='出售资产')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='products.product', verbose_name='商品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '出售挂单',
                'verbose_name_plural': '出售挂单',
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image_url', models.URLField(verbose_name='图片地址')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.listing', verbose_name='挂单')),
            ],
            options={
                'verbose_name': '挂单图片',
                'verbose_name_plural': '挂单图片',
                'db_table': 'listing_image',
                'ordering': ['sort_order'],
            },
        ),
    ]
