# Generated by Django 6.0.5 on 2026-06-02 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_userasset_owner'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='assets.userasset', verbose_name='出售资产'),
        ),
    ]
