# Generated by Django 6.0.5 on 2026-05-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOperationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('op_log_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='日志编号')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('target_id', models.CharField(blank=True, default='', max_length=50, verbose_name='操作对象编号')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作 IP')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
            ],
            options={
                'verbose_name': '管理员操作日志',
                'verbose_name_plural': '管理员操作日志',
                'db_table': 'admin_operation_log',
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('log_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='日志编号')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('target_id', models.CharField(blank=True, default='', max_length=50, verbose_name='操作对象编号')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作 IP')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_log',
            },
        ),
    ]
