# Generated by Django 6.0.5 on 2026-05-23 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exchange_id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='换物请求编号')),
                ('target_condition', models.TextField(blank=True, default='', verbose_name='目标条件')),
                ('price_difference_note', models.TextField(blank=True, default='', verbose_name='补差说明')),
                ('status', models.CharField(choices=[('active', '发布中'), ('matched', '已匹配'), ('completed', '已完成'), ('cancelled', '已取消'), ('expired', '已过期')], default='active', max_length=20, verbose_name='请求状态')),
                ('offered_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests', to='assets.userasset', verbose_name='发起方资产')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to=settings.AUTH_USER_MODEL, verbose_name='发起用户')),
            ],
            options={
                'verbose_name': '换物请求',
                'verbose_name_plural': '换物请求',
                'db_table': 'exchange_request',
            },
        ),
        migrations.CreateModel(
            name='ExchangeMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('match_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='匹配编号')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='匹配状态')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_matches', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
                ('applicant_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_matches', to='assets.userasset', verbose_name='申请方资产')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='exchanges.exchangerequest', verbose_name='关联换物请求')),
            ],
            options={
                'verbose_name': '换物匹配记录',
                'verbose_name_plural': '换物匹配记录',
                'db_table': 'exchange_match',
            },
        ),
        migrations.CreateModel(
            name='ExchangeStatusLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('log_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='日志编号')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='变更前状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='变更后状态')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='exchanges.exchangerequest', verbose_name='关联换物请求')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '换物状态变更记录',
                'verbose_name_plural': '换物状态变更记录',
                'db_table': 'exchange_status_log',
            },
        ),
    ]
