# Generated by Django 6.0.5 on 2026-06-02 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_userasset_owner'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangematch',
            name='applicant_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_matches', to='assets.userasset', verbose_name='申请方资产'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='offered_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='assets.userasset', verbose_name='发起方资产'),
        ),
    ]
